### ISSUE TITLE
Add Partial Resolver

### ISSUE THREAD

**Issue by guitarino** [ThaFog/Safetify#1]
Hello! Thanks for your work.

There are scenarios where I would like to resolve a partial object. For example, I would like to safely apply an update like so:

```typescript
type Person = {
    FirstName: string,
    LastName: string,
    Age: number
};

const person: Person = {
    FirstName: "John",
    LastName: "Dorian",
    Age: 30
};

// Potentially, this comes from a user end-point (i.e. we cannot rely on the type being proper)
const unsafePersonUpdate: Partial<Person> = {
    Age: 31
};

const personUpdateResolver: PartialResolver<Person> = PartialResolver<Person>({
    FirstName: StringResolver(),
    LastName: StringResolver(),
    Age: NumberResolver()
});

const resolveResponse = personUpdateResolver.resolve(unsafePersonUpdate);

const safeUpdate = resolveResponse.result;

const updatedPerson: Person = {
    ...person,
    ...safeUpdate
};

// And then maybe store a safe value somewhere
database.store(updatedPerson);
```

So, it would be nice to have a feature for Partial<> resolver.

**Comment by ThaFog** [comment]
Hey, thanks I'm glad you enjoy it!
Also this feature looks really good and for sure will be useful. Thought about it and decided to put it as `2.7.0` version omitting the fact that I'm working on `3.0.0` version with bigger refactor actually. Will handle this in the nearest time.

Thanks for this feature and consistent code!
